"""
report_generator.py — Generate downloadable PDF ATS report
Uses fpdf2 (lightweight, no LaTeX needed)
"""

import io
from typing import Dict, List
from datetime import datetime


def generate_pdf_report(
    filename: str,
    overall_score: float,
    section_scores: Dict[str, float],
    matched_keywords: List[str],
    missing_keywords: List[str],
    rewrite_text: str = "",
) -> bytes:
    """
    Build a PDF report and return as bytes.

    Args:
        filename: Resume filename
        overall_score: 0-100 ATS score
        section_scores: {skills, experience, education, other}
        matched_keywords: keywords found in both resume + JD
        missing_keywords: keywords in JD but missing from resume
        rewrite_text: optional AI-rewritten bullets

    Returns:
        PDF as bytes
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("fpdf2 not installed. Run: pip install fpdf2")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ──────────────────────────────────────────────────────────────
    pdf.set_fill_color(15, 15, 30)
    pdf.rect(0, 0, 210, 40, style="F")

    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_xy(10, 10)
    pdf.cell(0, 10, "HireMind AI — ATS Report", ln=True)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_xy(10, 24)
    pdf.cell(0, 6, f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}  |  File: {filename}")

    pdf.set_text_color(0, 0, 0)
    pdf.ln(20)

    # ── Overall Score ────────────────────────────────────────────────────────
    _section_header(pdf, "Overall ATS Score")
    score_color = (
        (239, 68, 68)  if overall_score < 50
        else (245, 158, 11) if overall_score < 75
        else (16, 185, 129)
    )
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(*score_color)
    pdf.cell(0, 16, f"{overall_score}%", ln=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Section Scores ───────────────────────────────────────────────────────
    _section_header(pdf, "Score Breakdown")
    pdf.set_font("Helvetica", "", 11)
    labels = {
        "skills":     "Skills Match",
        "experience": "Experience Match",
        "education":  "Education Match",
        "other":      "Other Keywords",
    }
    for key, label in labels.items():
        score = section_scores.get(key, 0)
        _score_bar(pdf, label, score)
    pdf.ln(4)

    # ── Matched Keywords ─────────────────────────────────────────────────────
    if matched_keywords:
        _section_header(pdf, f"Matched Keywords ({len(matched_keywords)})")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(16, 185, 129)
        _keyword_grid(pdf, matched_keywords[:30])
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # ── Missing Keywords ─────────────────────────────────────────────────────
    if missing_keywords:
        _section_header(pdf, f"Missing Keywords ({len(missing_keywords)})")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(239, 68, 68)
        _keyword_grid(pdf, missing_keywords[:30])
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # ── AI Rewrite ───────────────────────────────────────────────────────────
    if rewrite_text:
        pdf.add_page()
        _section_header(pdf, "AI-Improved Resume Bullets")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 80)
        # Clean and write line by line
        for line in rewrite_text.split("\n"):
            line = line.strip()
            if not line:
                pdf.ln(3)
                continue
            pdf.multi_cell(0, 5, line)
        pdf.set_text_color(0, 0, 0)

    # ── Footer ───────────────────────────────────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by HireMind AI · github.com/your-repo", align="C")

    return pdf.output()


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _section_header(pdf, title: str):
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(243, 244, 246)
    pdf.cell(0, 8, f"  {title}", ln=True, fill=True)
    pdf.ln(3)


def _score_bar(pdf, label: str, score: float):
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(70, 7, label)
    # Bar background
    pdf.set_fill_color(229, 231, 235)
    pdf.rect(pdf.get_x(), pdf.get_y() + 1, 90, 5, style="F")
    # Bar fill
    color = (239, 68, 68) if score < 50 else (245, 158, 11) if score < 75 else (16, 185, 129)
    pdf.set_fill_color(*color)
    pdf.rect(pdf.get_x(), pdf.get_y() + 1, 90 * (score / 100), 5, style="F")
    # Score text
    pdf.set_xy(pdf.get_x() + 95, pdf.get_y())
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(20, 7, f"{score}%", ln=True)
    pdf.ln(1)


def _keyword_grid(pdf, keywords: List[str], cols: int = 3):
    """Print keywords in a grid layout."""
    col_w = 60
    for i, kw in enumerate(keywords):
        pdf.cell(col_w, 6, f"✓ {kw[:25]}")
        if (i + 1) % cols == 0:
            pdf.ln()
    pdf.ln()
